using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SAPennant.API.Migrations
{
    public partial class AddHonourRoll : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "HonourRoll",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Year = table.Column<int>(nullable: false),
                    Competition = table.Column<string>(maxLength: 50, nullable: false),
                    Pool = table.Column<string>(maxLength: 50, nullable: false),
                    Winner = table.Column<string>(maxLength: 100, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_HonourRoll", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "HonourRollNarratives",
                columns: table => new
                {
                    Competition = table.Column<string>(maxLength: 50, nullable: false),
                    Narrative = table.Column<string>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_HonourRollNarratives", x => x.Competition);
                });

            // Narratives
            migrationBuilder.Sql(@"INSERT INTO HonourRollNarratives (Competition, Narrative) VALUES
(
    'Men''s',
    'The Simpson Cup, named after Mr Fred N Simpson, was inaugurated in 1927 and was originally for competition between Kooyonga Golf Club and Royal Adelaide Golf Club from 1927 to 1938. Post World War 2, The Grange Golf Club and Glenelg Golf Club entered the competition with the format being modified and altered from time to time with finals and additional club teams. Today, there are four divisions of Men''s Pennant – Simpson Cup, A2, Bonnar Cup and B2. Each club is represented by a seven-man team. The competing clubs are divided into divisions with a promotion/relegation system in operation to determine the composition of divisions for the following season. The Pennant Season is Round Robin match play contests between clubs at one venue in each division every week. At the conclusion of the minor round contest, the top four teams in each division compete in semi-finals to determine the top two teams to compete in the final to decide the divisional flags.'
),
(
    'Women''s',
    'Women''s Grade 1 Pennant commenced in 1930 and was administered by Women''s Golf South Australia (WGSA). In 2017, the Women''s A1 Pennant trophy was re-named after Pauline Sanderson as the Pauline Sanderson Cup. Pauline was inducted into the South Australian Golf Industry Hall of Fame in 2012 in recognition of her astounding contribution to South Australian Golf, both as a player and administrator. The Women''s A2 Pennant trophy was also re-named as the Pike Cup after Fiona Pike. Fiona was a prominent South Australian professional golfer for over 13 years. Fiona passed away in 2009 after a stoic three-year battle with skin cancer whose legacy lives on through the Fiona Pike Skin Cancer Awareness Campaign. Today, there are six divisions of Women''s Pennant – Sanderson Cup, Pike Cup, A3, A4, Cleek 1 and Cleek 2. Each club is represented by a five-person team. The competing clubs are divided into divisions with a promotion/relegation system in operation to determine the composition of divisions for the following season.'
),
(
    'Junior',
    'Junior Pennant is open to all male and female players under the age of 18 years. The Sharp Cup, which commenced in 1974, is named after William ''Bill'' Sharp who has a rich golfing history in South Australia. There are three divisions of Junior Pennant – Sharp Cup, Division 2 and Division 3. Each club is represented by a five-person team. The Pennant Season is Round Robin match play contests between clubs at one venue in each division every week. At the conclusion of the minor round contest, the top four teams in each division compete in semi-finals to determine the top two teams to compete in the final to decide the divisional flags. Sharp Cup is an off the stick competition while Division 2 and Division 3 are contested as handicap match play.'
),
(
    'Senior',
    'In 2007 eight golf clubs put together the concept and implemented a Seniors Pennant Golf Competition. The founding clubs were Mt Osmond, Blackwood, Flagstaff Hill, The Vines, Tea Tree Gully, Riverside (West Lakes), Thaxted Park and Mt Lofty (The Stirling). The Competition expanded over time as interest was generated amongst senior players in clubs. The Senior Pennant Competition now stands at nineteen clubs under the auspices of Golf Australia and is open to both male players aged 55 and above and female players aged 50 years and above as of the day of play.'
)");

            // Men's Pennant — Simpson Cup
            migrationBuilder.Sql(@"INSERT INTO HonourRoll (Year, Competition, Pool, Winner) VALUES
(2025,'Men''s','Simpson Cup','Glenelg'),
(2024,'Men''s','Simpson Cup','Kooyonga'),
(2023,'Men''s','Simpson Cup','Kooyonga'),
(2022,'Men''s','Simpson Cup','Kooyonga'),
(2021,'Men''s','Simpson Cup','Kooyonga'),
(2020,'Men''s','Simpson Cup',NULL),
(2019,'Men''s','Simpson Cup','Glenelg'),
(2018,'Men''s','Simpson Cup','Glenelg'),
(2017,'Men''s','Simpson Cup','Glenelg'),
(2016,'Men''s','Simpson Cup','Glenelg'),
(2015,'Men''s','Simpson Cup','Kooyonga'),
(2014,'Men''s','Simpson Cup','The Grange'),
(2013,'Men''s','Simpson Cup','Kooyonga'),
(2012,'Men''s','Simpson Cup','Tea Tree Gully'),
(2011,'Men''s','Simpson Cup','Tea Tree Gully'),
(2010,'Men''s','Simpson Cup','Tea Tree Gully'),
(2009,'Men''s','Simpson Cup','The Grange'),
(2008,'Men''s','Simpson Cup','The Grange'),
(2007,'Men''s','Simpson Cup','The Grange'),
(2006,'Men''s','Simpson Cup','Kooyonga'),
(2005,'Men''s','Simpson Cup','Kooyonga'),
(2004,'Men''s','Simpson Cup','Kooyonga'),
(2003,'Men''s','Simpson Cup','Glenelg'),
(2002,'Men''s','Simpson Cup','The Grange'),
(2001,'Men''s','Simpson Cup','Kooyonga'),
(2000,'Men''s','Simpson Cup','The Grange'),
(1999,'Men''s','Simpson Cup','The Grange'),
(1998,'Men''s','Simpson Cup','The Grange'),
(1997,'Men''s','Simpson Cup','Glenelg'),
(1996,'Men''s','Simpson Cup','Blackwood'),
(1995,'Men''s','Simpson Cup','Glenelg'),
(1994,'Men''s','Simpson Cup','Thaxted Park'),
(1993,'Men''s','Simpson Cup','Thaxted Park'),
(1992,'Men''s','Simpson Cup','The Grange'),
(1991,'Men''s','Simpson Cup','The Grange'),
(1990,'Men''s','Simpson Cup','Kooyonga'),
(1989,'Men''s','Simpson Cup','Kooyonga'),
(1988,'Men''s','Simpson Cup','Tea Tree Gully'),
(1987,'Men''s','Simpson Cup','Thaxted Park'),
(1986,'Men''s','Simpson Cup','The Grange'),
(1985,'Men''s','Simpson Cup','Glenelg'),
(1984,'Men''s','Simpson Cup','The Grange'),
(1983,'Men''s','Simpson Cup','Thaxted Park'),
(1982,'Men''s','Simpson Cup','The Grange'),
(1981,'Men''s','Simpson Cup','The Grange'),
(1980,'Men''s','Simpson Cup','The Grange'),
(1979,'Men''s','Simpson Cup','The Grange'),
(1978,'Men''s','Simpson Cup','Kooyonga'),
(1977,'Men''s','Simpson Cup','Kooyonga'),
(1976,'Men''s','Simpson Cup','Kooyonga'),
(1975,'Men''s','Simpson Cup','Kooyonga'),
(1974,'Men''s','Simpson Cup','Kooyonga'),
(1973,'Men''s','Simpson Cup','The Grange'),
(1972,'Men''s','Simpson Cup','The Grange'),
(1971,'Men''s','Simpson Cup','The Grange'),
(1970,'Men''s','Simpson Cup','Kooyonga'),
(1969,'Men''s','Simpson Cup','The Grange'),
(1968,'Men''s','Simpson Cup','Glenelg'),
(1967,'Men''s','Simpson Cup','The Grange'),
(1966,'Men''s','Simpson Cup','Kooyonga'),
(1965,'Men''s','Simpson Cup','Glenelg'),
(1964,'Men''s','Simpson Cup','Kooyonga'),
(1963,'Men''s','Simpson Cup','Glenelg'),
(1962,'Men''s','Simpson Cup','Kooyonga'),
(1961,'Men''s','Simpson Cup','The Grange'),
(1960,'Men''s','Simpson Cup','Kooyonga'),
(1959,'Men''s','Simpson Cup','Kooyonga'),
(1958,'Men''s','Simpson Cup','Glenelg'),
(1957,'Men''s','Simpson Cup','Kooyonga'),
(1956,'Men''s','Simpson Cup','Kooyonga'),
(1955,'Men''s','Simpson Cup','Glenelg'),
(1954,'Men''s','Simpson Cup','Kooyonga'),
(1953,'Men''s','Simpson Cup','Kooyonga'),
(1952,'Men''s','Simpson Cup','Kooyonga'),
(1951,'Men''s','Simpson Cup','Royal Adelaide'),
(1950,'Men''s','Simpson Cup','Kooyonga'),
(1949,'Men''s','Simpson Cup','Kooyonga'),
(1948,'Men''s','Simpson Cup','Kooyonga'),
(1947,'Men''s','Simpson Cup','Kooyonga'),
(1946,'Men''s','Simpson Cup','Kooyonga'),
(1939,'Men''s','Simpson Cup','Royal Adelaide'),
(1938,'Men''s','Simpson Cup','Royal Adelaide'),
(1937,'Men''s','Simpson Cup','Royal Adelaide'),
(1936,'Men''s','Simpson Cup','Royal Adelaide'),
(1935,'Men''s','Simpson Cup','Royal Adelaide'),
(1934,'Men''s','Simpson Cup','Kooyonga'),
(1933,'Men''s','Simpson Cup','Royal Adelaide'),
(1932,'Men''s','Simpson Cup','Royal Adelaide'),
(1931,'Men''s','Simpson Cup','Kooyonga'),
(1930,'Men''s','Simpson Cup','Royal Adelaide'),
(1929,'Men''s','Simpson Cup','Kooyonga'),
(1928,'Men''s','Simpson Cup','Kooyonga'),
(1927,'Men''s','Simpson Cup','Royal Adelaide')");

            // Men's Pennant — Bonnar Cup
            migrationBuilder.Sql(@"INSERT INTO HonourRoll (Year, Competition, Pool, Winner) VALUES
(2025,'Men''s','Bonnar Cup','Glenelg'),
(2024,'Men''s','Bonnar Cup','Royal Adelaide'),
(2023,'Men''s','Bonnar Cup','Glenelg'),
(2022,'Men''s','Bonnar Cup','The Grange'),
(2021,'Men''s','Bonnar Cup','The Grange'),
(2020,'Men''s','Bonnar Cup',NULL),
(2019,'Men''s','Bonnar Cup','Glenelg'),
(2018,'Men''s','Bonnar Cup','The Grange'),
(2017,'Men''s','Bonnar Cup','Glenelg'),
(2016,'Men''s','Bonnar Cup','The Grange'),
(2015,'Men''s','Bonnar Cup','The Grange'),
(2014,'Men''s','Bonnar Cup','Glenelg'),
(2013,'Men''s','Bonnar Cup','The Grange'),
(2012,'Men''s','Bonnar Cup','Tea Tree Gully'),
(2011,'Men''s','Bonnar Cup','The Grange'),
(2010,'Men''s','Bonnar Cup','Tea Tree Gully'),
(2009,'Men''s','Bonnar Cup','Kooyonga'),
(2008,'Men''s','Bonnar Cup','Glenelg'),
(2007,'Men''s','Bonnar Cup','Royal Adelaide'),
(2006,'Men''s','Bonnar Cup','Glenelg'),
(2005,'Men''s','Bonnar Cup','The Grange'),
(2004,'Men''s','Bonnar Cup','Highercombe'),
(2003,'Men''s','Bonnar Cup','Flagstaff Hill'),
(2002,'Men''s','Bonnar Cup','The Grange'),
(2001,'Men''s','Bonnar Cup','Tea Tree Gully'),
(2000,'Men''s','Bonnar Cup','Blackwood'),
(1999,'Men''s','Bonnar Cup','Blackwood'),
(1998,'Men''s','Bonnar Cup','Blackwood'),
(1997,'Men''s','Bonnar Cup','Blackwood'),
(1996,'Men''s','Bonnar Cup','Blackwood'),
(1995,'Men''s','Bonnar Cup','Blackwood'),
(1994,'Men''s','Bonnar Cup','The Grange'),
(1993,'Men''s','Bonnar Cup','Blackwood'),
(1992,'Men''s','Bonnar Cup','Blackwood'),
(1991,'Men''s','Bonnar Cup','The Grange'),
(1990,'Men''s','Bonnar Cup','The Grange'),
(1989,'Men''s','Bonnar Cup','The Grange'),
(1988,'Men''s','Bonnar Cup','The Grange'),
(1987,'Men''s','Bonnar Cup','Thaxted Park'),
(1986,'Men''s','Bonnar Cup','The Grange'),
(1985,'Men''s','Bonnar Cup','The Grange'),
(1984,'Men''s','Bonnar Cup','The Grange'),
(1983,'Men''s','Bonnar Cup','The Grange'),
(1982,'Men''s','Bonnar Cup','Glenelg'),
(1981,'Men''s','Bonnar Cup','Glenelg'),
(1980,'Men''s','Bonnar Cup','The Grange'),
(1979,'Men''s','Bonnar Cup','The Grange'),
(1978,'Men''s','Bonnar Cup','Glenelg'),
(1977,'Men''s','Bonnar Cup','Kooyonga'),
(1976,'Men''s','Bonnar Cup','The Grange'),
(1975,'Men''s','Bonnar Cup','Glenelg'),
(1974,'Men''s','Bonnar Cup','Kooyonga'),
(1973,'Men''s','Bonnar Cup','Blackwood'),
(1972,'Men''s','Bonnar Cup','Kooyonga'),
(1971,'Men''s','Bonnar Cup','Riverside'),
(1970,'Men''s','Bonnar Cup','Glenelg'),
(1969,'Men''s','Bonnar Cup','Kooyonga'),
(1968,'Men''s','Bonnar Cup','Tea Tree Gully'),
(1967,'Men''s','Bonnar Cup','Kooyonga'),
(1966,'Men''s','Bonnar Cup','Kooyonga'),
(1965,'Men''s','Bonnar Cup','North Adelaide'),
(1964,'Men''s','Bonnar Cup','Kooyonga'),
(1963,'Men''s','Bonnar Cup','Kooyonga'),
(1962,'Men''s','Bonnar Cup','North Adelaide'),
(1961,'Men''s','Bonnar Cup','Glenelg'),
(1960,'Men''s','Bonnar Cup','The Grange'),
(1959,'Men''s','Bonnar Cup','Glenelg'),
(1958,'Men''s','Bonnar Cup','Kooyonga'),
(1957,'Men''s','Bonnar Cup','North Adelaide'),
(1956,'Men''s','Bonnar Cup','Glenelg'),
(1955,'Men''s','Bonnar Cup','The Grange')");

            // Men's Pennant — Men's A2
            migrationBuilder.Sql(@"INSERT INTO HonourRoll (Year, Competition, Pool, Winner) VALUES
(2025,'Men''s','Men''s A2','Mount Osmond'),
(2024,'Men''s','Men''s A2','Southern'),
(2023,'Men''s','Men''s A2','Mount Osmond'),
(2022,'Men''s','Men''s A2','Thaxted Park'),
(2021,'Men''s','Men''s A2','Tea Tree Gully'),
(2020,'Men''s','Men''s A2',NULL),
(2019,'Men''s','Men''s A2','Flagstaff Hill'),
(2018,'Men''s','Men''s A2','Mid North'),
(2017,'Men''s','Men''s A2','Royal Adelaide'),
(2016,'Men''s','Men''s A2','Thaxted Park'),
(2015,'Men''s','Men''s A2','Southern'),
(2014,'Men''s','Men''s A2','The Vines'),
(2013,'Men''s','Men''s A2','Blackwood'),
(2012,'Men''s','Men''s A2','Mount Lofty'),
(2011,'Men''s','Men''s A2','Highercombe'),
(2010,'Men''s','Men''s A2','Thaxted Park'),
(2009,'Men''s','Men''s A2','Highercombe')");

            // Men's Pennant — Men's B2
            migrationBuilder.Sql(@"INSERT INTO HonourRoll (Year, Competition, Pool, Winner) VALUES
(2025,'Men''s','Men''s B2','Aston Hills'),
(2024,'Men''s','Men''s B2','Westward Ho'),
(2023,'Men''s','Men''s B2','Thaxted Park'),
(2022,'Men''s','Men''s B2','Regency Park'),
(2021,'Men''s','Men''s B2','Royal Adelaide'),
(2020,'Men''s','Men''s B2',NULL),
(2019,'Men''s','Men''s B2','Tea Tree Gully'),
(2018,'Men''s','Men''s B2','Regency Park'),
(2017,'Men''s','Men''s B2','North Adelaide'),
(2016,'Men''s','Men''s B2','Royal Adelaide'),
(2015,'Men''s','Men''s B2','Flagstaff Hill'),
(2014,'Men''s','Men''s B2','North Adelaide'),
(2013,'Men''s','Men''s B2','Mount Osmond'),
(2012,'Men''s','Men''s B2','Blackwood'),
(2011,'Men''s','Men''s B2','North Adelaide'),
(2010,'Men''s','Men''s B2','Flagstaff Hill'),
(2009,'Men''s','Men''s B2','Tea Tree Gully')");

            // Women's Pennant — Sanderson Cup
            migrationBuilder.Sql(@"INSERT INTO HonourRoll (Year, Competition, Pool, Winner) VALUES
(2025,'Women''s','Sanderson Cup','Glenelg'),
(2024,'Women''s','Sanderson Cup','Kooyonga'),
(2023,'Women''s','Sanderson Cup','Kooyonga'),
(2022,'Women''s','Sanderson Cup','The Grange'),
(2021,'Women''s','Sanderson Cup','The Grange'),
(2020,'Women''s','Sanderson Cup',NULL),
(2019,'Women''s','Sanderson Cup','Glenelg'),
(2018,'Women''s','Sanderson Cup','The Grange'),
(2017,'Women''s','Sanderson Cup','The Grange'),
(2016,'Women''s','Sanderson Cup','The Grange'),
(2015,'Women''s','Sanderson Cup','The Grange'),
(2014,'Women''s','Sanderson Cup','Glenelg'),
(2013,'Women''s','Sanderson Cup','Glenelg'),
(2012,'Women''s','Sanderson Cup','Glenelg'),
(2011,'Women''s','Sanderson Cup','Royal Adelaide'),
(2010,'Women''s','Sanderson Cup','Royal Adelaide'),
(2009,'Women''s','Sanderson Cup','Glenelg'),
(2008,'Women''s','Sanderson Cup','Royal Adelaide'),
(2007,'Women''s','Sanderson Cup','Royal Adelaide'),
(2006,'Women''s','Sanderson Cup','Kooyonga'),
(2005,'Women''s','Sanderson Cup','Glenelg'),
(2004,'Women''s','Sanderson Cup','The Grange'),
(2003,'Women''s','Sanderson Cup','Kooyonga'),
(2002,'Women''s','Sanderson Cup','Kooyonga'),
(2001,'Women''s','Sanderson Cup','Kooyonga'),
(2000,'Women''s','Sanderson Cup','Fringe'),
(1999,'Women''s','Sanderson Cup','Kooyonga'),
(1998,'Women''s','Sanderson Cup','Glenelg'),
(1997,'Women''s','Sanderson Cup','Kooyonga'),
(1996,'Women''s','Sanderson Cup','Fringe'),
(1995,'Women''s','Sanderson Cup','Kooyonga'),
(1994,'Women''s','Sanderson Cup','Kooyonga'),
(1993,'Women''s','Sanderson Cup','Blackwood'),
(1992,'Women''s','Sanderson Cup','Glenelg'),
(1991,'Women''s','Sanderson Cup','Glenelg'),
(1990,'Women''s','Sanderson Cup','Kooyonga'),
(1989,'Women''s','Sanderson Cup','Kooyonga'),
(1988,'Women''s','Sanderson Cup','Blackwood'),
(1987,'Women''s','Sanderson Cup','Kooyonga'),
(1986,'Women''s','Sanderson Cup','Glenelg'),
(1985,'Women''s','Sanderson Cup','The Grange'),
(1984,'Women''s','Sanderson Cup','The Grange'),
(1983,'Women''s','Sanderson Cup','Kooyonga'),
(1982,'Women''s','Sanderson Cup','The Grange'),
(1981,'Women''s','Sanderson Cup','Glenelg'),
(1980,'Women''s','Sanderson Cup','Kooyonga'),
(1979,'Women''s','Sanderson Cup','Kooyonga'),
(1978,'Women''s','Sanderson Cup','Kooyonga'),
(1977,'Women''s','Sanderson Cup','Kooyonga'),
(1976,'Women''s','Sanderson Cup','Glenelg'),
(1975,'Women''s','Sanderson Cup','Kooyonga'),
(1974,'Women''s','Sanderson Cup','Tea Tree Gully'),
(1973,'Women''s','Sanderson Cup','Glenelg'),
(1972,'Women''s','Sanderson Cup','Glenelg'),
(1971,'Women''s','Sanderson Cup','Kooyonga'),
(1970,'Women''s','Sanderson Cup','Kooyonga'),
(1969,'Women''s','Sanderson Cup','Kooyonga'),
(1968,'Women''s','Sanderson Cup','Kooyonga'),
(1967,'Women''s','Sanderson Cup','Glenelg'),
(1966,'Women''s','Sanderson Cup','Glenelg'),
(1965,'Women''s','Sanderson Cup','Glenelg'),
(1964,'Women''s','Sanderson Cup','Glenelg'),
(1963,'Women''s','Sanderson Cup','Kooyonga'),
(1962,'Women''s','Sanderson Cup','Kooyonga'),
(1961,'Women''s','Sanderson Cup','Glenelg'),
(1960,'Women''s','Sanderson Cup','Kooyonga'),
(1959,'Women''s','Sanderson Cup','Glenelg'),
(1958,'Women''s','Sanderson Cup','Kooyonga'),
(1957,'Women''s','Sanderson Cup','Glenelg'),
(1956,'Women''s','Sanderson Cup','Kooyonga'),
(1955,'Women''s','Sanderson Cup','Kooyonga'),
(1954,'Women''s','Sanderson Cup','Royal Adelaide'),
(1953,'Women''s','Sanderson Cup','Kooyonga'),
(1952,'Women''s','Sanderson Cup','Kooyonga'),
(1951,'Women''s','Sanderson Cup','Kooyonga'),
(1950,'Women''s','Sanderson Cup','Kooyonga'),
(1949,'Women''s','Sanderson Cup','Kooyonga'),
(1948,'Women''s','Sanderson Cup','Kooyonga'),
(1947,'Women''s','Sanderson Cup','Royal Adelaide'),
(1940,'Women''s','Sanderson Cup','Glenelg'),
(1939,'Women''s','Sanderson Cup','Royal Adelaide'),
(1938,'Women''s','Sanderson Cup','Royal Adelaide'),
(1937,'Women''s','Sanderson Cup','Kooyonga'),
(1936,'Women''s','Sanderson Cup','Kooyonga'),
(1935,'Women''s','Sanderson Cup','Royal Adelaide'),
(1934,'Women''s','Sanderson Cup','Royal Adelaide'),
(1933,'Women''s','Sanderson Cup','Royal Adelaide'),
(1932,'Women''s','Sanderson Cup','Kooyonga'),
(1931,'Women''s','Sanderson Cup','Royal Adelaide'),
(1930,'Women''s','Sanderson Cup','Kooyonga')");

            // Women's Pennant — Pike Cup
            migrationBuilder.Sql(@"INSERT INTO HonourRoll (Year, Competition, Pool, Winner) VALUES
(2025,'Women''s','Pike Cup','Kooyonga'),
(2024,'Women''s','Pike Cup','Royal Adelaide'),
(2023,'Women''s','Pike Cup','Glenelg'),
(2022,'Women''s','Pike Cup','Glenelg'),
(2021,'Women''s','Pike Cup','Glenelg'),
(2020,'Women''s','Pike Cup',NULL),
(2019,'Women''s','Pike Cup','The Grange'),
(2018,'Women''s','Pike Cup','Glenelg'),
(2017,'Women''s','Pike Cup','Glenelg'),
(2016,'Women''s','Pike Cup','The Vines'),
(2015,'Women''s','Pike Cup','The Grange'),
(2014,'Women''s','Pike Cup','Kooyonga'),
(2013,'Women''s','Pike Cup','Royal Adelaide'),
(2012,'Women''s','Pike Cup','Glenelg'),
(2011,'Women''s','Pike Cup','Royal Adelaide'),
(2010,'Women''s','Pike Cup','Mount Osmond'),
(2009,'Women''s','Pike Cup','Kooyonga'),
(2008,'Women''s','Pike Cup','Glenelg'),
(2007,'Women''s','Pike Cup','Royal Adelaide'),
(2006,'Women''s','Pike Cup','Mount Osmond'),
(2005,'Women''s','Pike Cup','Royal Adelaide'),
(2004,'Women''s','Pike Cup','Kooyonga'),
(2003,'Women''s','Pike Cup','Kooyonga'),
(2002,'Women''s','Pike Cup','Glenelg'),
(2001,'Women''s','Pike Cup','Glenelg'),
(2000,'Women''s','Pike Cup','Tea Tree Gully'),
(1999,'Women''s','Pike Cup','Tea Tree Gully'),
(1998,'Women''s','Pike Cup','Kooyonga'),
(1997,'Women''s','Pike Cup','Tea Tree Gully'),
(1996,'Women''s','Pike Cup','Royal Adelaide'),
(1995,'Women''s','Pike Cup','The Grange'),
(1994,'Women''s','Pike Cup','Marino'),
(1993,'Women''s','Pike Cup','The Grange'),
(1992,'Women''s','Pike Cup','Royal Adelaide'),
(1991,'Women''s','Pike Cup','Kooyonga'),
(1990,'Women''s','Pike Cup','Glenelg'),
(1989,'Women''s','Pike Cup','Marino'),
(1988,'Women''s','Pike Cup','Royal Adelaide'),
(1987,'Women''s','Pike Cup','Marino'),
(1986,'Women''s','Pike Cup','Thaxted Park'),
(1985,'Women''s','Pike Cup','Thaxted Park'),
(1984,'Women''s','Pike Cup','Kooyonga'),
(1983,'Women''s','Pike Cup','Kooyonga'),
(1982,'Women''s','Pike Cup','Blackwood'),
(1981,'Women''s','Pike Cup','Kooyonga'),
(1980,'Women''s','Pike Cup','Royal Adelaide'),
(1979,'Women''s','Pike Cup','The Grange'),
(1978,'Women''s','Pike Cup','Tea Tree Gully'),
(1977,'Women''s','Pike Cup','Mount Osmond'),
(1976,'Women''s','Pike Cup','Glenelg'),
(1975,'Women''s','Pike Cup','Riverside'),
(1974,'Women''s','Pike Cup','The Grange'),
(1973,'Women''s','Pike Cup','Mount Osmond'),
(1972,'Women''s','Pike Cup','Tea Tree Gully'),
(1971,'Women''s','Pike Cup','Tea Tree Gully'),
(1970,'Women''s','Pike Cup','Kooyonga'),
(1969,'Women''s','Pike Cup','Kooyonga'),
(1968,'Women''s','Pike Cup','Mount Osmond'),
(1967,'Women''s','Pike Cup','Glenelg'),
(1966,'Women''s','Pike Cup','Glenelg'),
(1965,'Women''s','Pike Cup','Glenelg'),
(1964,'Women''s','Pike Cup','Glenelg'),
(1963,'Women''s','Pike Cup','Glenelg'),
(1962,'Women''s','Pike Cup','Glenelg'),
(1961,'Women''s','Pike Cup','Glenelg'),
(1960,'Women''s','Pike Cup','Kooyonga'),
(1959,'Women''s','Pike Cup','Glenelg'),
(1958,'Women''s','Pike Cup','Royal Adelaide'),
(1957,'Women''s','Pike Cup','Royal Adelaide'),
(1956,'Women''s','Pike Cup','Royal Adelaide'),
(1955,'Women''s','Pike Cup','Royal Adelaide'),
(1954,'Women''s','Pike Cup','Kooyonga')");

            // Women's Pennant — Women's A3
            migrationBuilder.Sql(@"INSERT INTO HonourRoll (Year, Competition, Pool, Winner) VALUES
(2025,'Women''s','Women''s A3','The Vines'),
(2024,'Women''s','Women''s A3','Mount Osmond'),
(2023,'Women''s','Women''s A3','West Lakes'),
(2022,'Women''s','Women''s A3','West Lakes'),
(2021,'Women''s','Women''s A3','North Adelaide'),
(2020,'Women''s','Women''s A3',NULL),
(2019,'Women''s','Women''s A3','Glenelg'),
(2018,'Women''s','Women''s A3','Glenelg'),
(2017,'Women''s','Women''s A3','Tea Tree Gully'),
(2016,'Women''s','Women''s A3','Royal Adelaide'),
(2015,'Women''s','Women''s A3','Royal Adelaide'),
(2014,'Women''s','Women''s A3','Tea Tree Gully'),
(2013,'Women''s','Women''s A3','Flagstaff Hill'),
(2012,'Women''s','Women''s A3','Kooyonga'),
(2011,'Women''s','Women''s A3','The Vines'),
(2010,'Women''s','Women''s A3','Blackwood'),
(2009,'Women''s','Women''s A3','Thaxted Park'),
(2008,'Women''s','Women''s A3','Flagstaff Hill'),
(2005,'Women''s','Women''s A3','Mount Lofty'),
(2004,'Women''s','Women''s A3','Mount Lofty'),
(2003,'Women''s','Women''s A3','Mount Osmond'),
(2002,'Women''s','Women''s A3','Mount Osmond'),
(2001,'Women''s','Women''s A3','Mount Osmond'),
(2000,'Women''s','Women''s A3','Tea Tree Gully'),
(1999,'Women''s','Women''s A3','Tea Tree Gully'),
(1998,'Women''s','Women''s A3','The Grange'),
(1997,'Women''s','Women''s A3','Flagstaff Hill'),
(1996,'Women''s','Women''s A3','North Adelaide'),
(1995,'Women''s','Women''s A3','Flagstaff Hill'),
(1989,'Women''s','Women''s A3','Kooyonga'),
(1988,'Women''s','Women''s A3','Glenelg'),
(1987,'Women''s','Women''s A3','Flagstaff Hill'),
(1986,'Women''s','Women''s A3','Mount Osmond'),
(1985,'Women''s','Women''s A3','Mount Osmond'),
(1984,'Women''s','Women''s A3','Tea Tree Gully'),
(1983,'Women''s','Women''s A3','Royal Adelaide'),
(1982,'Women''s','Women''s A3','Thaxted Park'),
(1981,'Women''s','Women''s A3','Blackwood'),
(1980,'Women''s','Women''s A3','Flagstaff Hill'),
(1979,'Women''s','Women''s A3','Flagstaff Hill'),
(1978,'Women''s','Women''s A3','Glenelg'),
(1977,'Women''s','Women''s A3','Blackwood'),
(1976,'Women''s','Women''s A3','Blackwood'),
(1975,'Women''s','Women''s A3','Glenelg'),
(1974,'Women''s','Women''s A3','Tea Tree Gully'),
(1973,'Women''s','Women''s A3','Thaxted Park'),
(1972,'Women''s','Women''s A3','Royal Adelaide'),
(1971,'Women''s','Women''s A3','Riverside'),
(1970,'Women''s','Women''s A3','Marino'),
(1969,'Women''s','Women''s A3','Tea Tree Gully'),
(1968,'Women''s','Women''s A3','Westward Ho'),
(1967,'Women''s','Women''s A3','Glenelg'),
(1966,'Women''s','Women''s A3','Blackwood'),
(1965,'Women''s','Women''s A3','Marino'),
(1964,'Women''s','Women''s A3','Westward Ho'),
(1963,'Women''s','Women''s A3','Westward Ho'),
(1962,'Women''s','Women''s A3','Riverside'),
(1961,'Women''s','Women''s A3','Marino'),
(1960,'Women''s','Women''s A3','Blackwood'),
(1959,'Women''s','Women''s A3','Blackwood'),
(1958,'Women''s','Women''s A3','Blackwood'),
(1957,'Women''s','Women''s A3','Blackwood'),
(1956,'Women''s','Women''s A3','Blackwood'),
(1955,'Women''s','Women''s A3','Riverside')");

            // Women's Pennant — Women's A4
            migrationBuilder.Sql(@"INSERT INTO HonourRoll (Year, Competition, Pool, Winner) VALUES
(2025,'Women''s','Women''s A4','Kooyonga'),
(2024,'Women''s','Women''s A4','The Grange'),
(2023,'Women''s','Women''s A4','Highercombe'),
(2022,'Women''s','Women''s A4','Royal Adelaide'),
(2021,'Women''s','Women''s A4','The Vines'),
(2020,'Women''s','Women''s A4',NULL),
(2019,'Women''s','Women''s A4','The Grange'),
(2018,'Women''s','Women''s A4','Kooyonga'),
(2017,'Women''s','Women''s A4','Glenelg')");

            // Women's Pennant — Cleek 1
            migrationBuilder.Sql(@"INSERT INTO HonourRoll (Year, Competition, Pool, Winner) VALUES
(2025,'Women''s','Women''s Cleek 1','Thaxted Park'),
(2024,'Women''s','Women''s Cleek 1','West Lakes'),
(2023,'Women''s','Women''s Cleek 1','Royal Adelaide'),
(2022,'Women''s','Women''s Cleek 1','North Adelaide'),
(2021,'Women''s','Women''s Cleek 1','Mount Osmond'),
(2020,'Women''s','Women''s Cleek 1',NULL),
(2019,'Women''s','Women''s Cleek 1','Flagstaff Hill'),
(2018,'Women''s','Women''s Cleek 1','Mount Osmond'),
(2017,'Women''s','Women''s Cleek 1','The Grange'),
(2016,'Women''s','Women''s Cleek 1','Royal Adelaide'),
(2015,'Women''s','Women''s Cleek 1','Kooyonga'),
(2014,'Women''s','Women''s Cleek 1','Mount Osmond'),
(2013,'Women''s','Women''s Cleek 1','Mount Osmond'),
(2012,'Women''s','Women''s Cleek 1','West Lakes'),
(2011,'Women''s','Women''s Cleek 1','Glenelg'),
(2010,'Women''s','Women''s Cleek 1','Royal Adelaide'),
(2009,'Women''s','Women''s Cleek 1','Riverside'),
(2008,'Women''s','Women''s Cleek 1','Tea Tree Gully'),
(2007,'Women''s','Women''s Cleek 1','Glenelg'),
(2006,'Women''s','Women''s Cleek 1','Blackwood'),
(2005,'Women''s','Women''s Cleek 1','Tea Tree Gully'),
(2004,'Women''s','Women''s Cleek 1','Riverside'),
(2003,'Women''s','Women''s Cleek 1','Royal Adelaide'),
(2002,'Women''s','Women''s Cleek 1','Riverside'),
(2001,'Women''s','Women''s Cleek 1','Royal Adelaide'),
(2000,'Women''s','Women''s Cleek 1','Tea Tree Gully'),
(1999,'Women''s','Women''s Cleek 1','Tea Tree Gully'),
(1998,'Women''s','Women''s Cleek 1','Riverside'),
(1997,'Women''s','Women''s Cleek 1','Riverside')");

            // Women's Pennant — Cleek 2
            migrationBuilder.Sql(@"INSERT INTO HonourRoll (Year, Competition, Pool, Winner) VALUES
(2025,'Women''s','Women''s Cleek 2','North Adelaide'),
(2024,'Women''s','Women''s Cleek 2','Westward Ho'),
(2023,'Women''s','Women''s Cleek 2','Tea Tree Gully'),
(2022,'Women''s','Women''s Cleek 2','Kooyonga'),
(2021,'Women''s','Women''s Cleek 2','Blackwood'),
(2020,'Women''s','Women''s Cleek 2',NULL),
(2019,'Women''s','Women''s Cleek 2','Thaxted Park'),
(2018,'Women''s','Women''s Cleek 2','Royal Adelaide'),
(2017,'Women''s','Women''s Cleek 2','The Vines'),
(2016,'Women''s','Women''s Cleek 2','North Adelaide'),
(2015,'Women''s','Women''s Cleek 2','West Lakes'),
(2014,'Women''s','Women''s Cleek 2','Flagstaff Hill'),
(2013,'Women''s','Women''s Cleek 2','Blackwood'),
(2012,'Women''s','Women''s Cleek 2','Mount Osmond'),
(2011,'Women''s','Women''s Cleek 2','Flagstaff Hill')");

            // Junior Pennant — Sharp Cup
            migrationBuilder.Sql(@"INSERT INTO HonourRoll (Year, Competition, Pool, Winner) VALUES
(2025,'Junior','Sharp Cup','Royal Adelaide'),
(2024,'Junior','Sharp Cup','The Grange'),
(2023,'Junior','Sharp Cup','Glenelg'),
(2022,'Junior','Sharp Cup','Glenelg'),
(2021,'Junior','Sharp Cup','Glenelg'),
(2020,'Junior','Sharp Cup',NULL),
(2019,'Junior','Sharp Cup','The Vines'),
(2018,'Junior','Sharp Cup','Kooyonga'),
(2017,'Junior','Sharp Cup','Glenelg'),
(2016,'Junior','Sharp Cup','Glenelg'),
(2015,'Junior','Sharp Cup','Kooyonga'),
(2014,'Junior','Sharp Cup','The Grange'),
(2013,'Junior','Sharp Cup','Kooyonga'),
(2012,'Junior','Sharp Cup','The Grange'),
(2011,'Junior','Sharp Cup','The Grange'),
(2010,'Junior','Sharp Cup','The Grange'),
(2009,'Junior','Sharp Cup','Kooyonga'),
(2008,'Junior','Sharp Cup','Kooyonga'),
(2007,'Junior','Sharp Cup','Kooyonga'),
(2006,'Junior','Sharp Cup','Glenelg'),
(2005,'Junior','Sharp Cup','Kooyonga'),
(2004,'Junior','Sharp Cup','Kooyonga'),
(2003,'Junior','Sharp Cup','Tea Tree Gully'),
(2002,'Junior','Sharp Cup','The Grange'),
(2001,'Junior','Sharp Cup','The Grange'),
(2000,'Junior','Sharp Cup','Tea Tree Gully'),
(1999,'Junior','Sharp Cup','Thaxted Park'),
(1998,'Junior','Sharp Cup','The Grange'),
(1997,'Junior','Sharp Cup','Flagstaff Hill'),
(1996,'Junior','Sharp Cup','The Grange'),
(1995,'Junior','Sharp Cup','Thaxted Park'),
(1994,'Junior','Sharp Cup','Marino'),
(1993,'Junior','Sharp Cup','The Grange'),
(1992,'Junior','Sharp Cup','Blackwood'),
(1991,'Junior','Sharp Cup','Kooyonga'),
(1990,'Junior','Sharp Cup','The Grange'),
(1989,'Junior','Sharp Cup','Kooyonga'),
(1988,'Junior','Sharp Cup','Kooyonga'),
(1983,'Junior','Sharp Cup','Thaxted Park'),
(1982,'Junior','Sharp Cup','Riverside'),
(1981,'Junior','Sharp Cup','Riverside'),
(1980,'Junior','Sharp Cup','Glenelg'),
(1979,'Junior','Sharp Cup','Glenelg'),
(1978,'Junior','Sharp Cup','Kooyonga'),
(1977,'Junior','Sharp Cup','Kooyonga'),
(1976,'Junior','Sharp Cup','Kooyonga'),
(1975,'Junior','Sharp Cup','Tea Tree Gully'),
(1974,'Junior','Sharp Cup','Kooyonga')");

            // Junior Pennant — Division 2
            migrationBuilder.Sql(@"INSERT INTO HonourRoll (Year, Competition, Pool, Winner) VALUES
(2025,'Junior','Junior Division 2','Kooyonga'),
(2024,'Junior','Junior Division 2','The Grange'),
(2023,'Junior','Junior Division 2','Country Districts'),
(2022,'Junior','Junior Division 2','The Vines'),
(2021,'Junior','Junior Division 2','Tea Tree Gully'),
(2020,'Junior','Junior Division 2',NULL),
(2019,'Junior','Junior Division 2','Country District'),
(2018,'Junior','Junior Division 2','The Vines'),
(2017,'Junior','Junior Division 2','The Vines'),
(2016,'Junior','Junior Division 2','West Lakes'),
(2015,'Junior','Junior Division 2','The Grange'),
(2014,'Junior','Junior Division 2','West Lakes')");

            // Junior Pennant — Division 3
            migrationBuilder.Sql(@"INSERT INTO HonourRoll (Year, Competition, Pool, Winner) VALUES
(2025,'Junior','Junior Division 3','Mid North'),
(2024,'Junior','Junior Division 3','Westward Ho')");

            // Senior Pennant — Division 1
            migrationBuilder.Sql(@"INSERT INTO HonourRoll (Year, Competition, Pool, Winner) VALUES
(2025,'Senior','Senior Division 1','The Vines'),
(2024,'Senior','Senior Division 1','The Vines'),
(2023,'Senior','Senior Division 1','Glenelg'),
(2022,'Senior','Senior Division 1','Tea Tree Gully'),
(2021,'Senior','Senior Division 1','Tea Tree Gully'),
(2020,'Senior','Senior Division 1','Blackwood'),
(2019,'Senior','Senior Division 1','Tea Tree Gully'),
(2018,'Senior','Senior Division 1','Tea Tree Gully'),
(2017,'Senior','Senior Division 1','Tea Tree Gully'),
(2016,'Senior','Senior Division 1','Tea Tree Gully'),
(2015,'Senior','Senior Division 1','Tea Tree Gully'),
(2014,'Senior','Senior Division 1','Tea Tree Gully'),
(2013,'Senior','Senior Division 1','Tea Tree Gully'),
(2012,'Senior','Senior Division 1','Tea Tree Gully'),
(2011,'Senior','Senior Division 1','Tea Tree Gully'),
(2010,'Senior','Senior Division 1','Tea Tree Gully'),
(2009,'Senior','Senior Division 1','Tea Tree Gully'),
(2008,'Senior','Senior Division 1','Tea Tree Gully'),
(2007,'Senior','Senior Division 1','Tea Tree Gully')");

            // Senior Pennant — Division 2
            migrationBuilder.Sql(@"INSERT INTO HonourRoll (Year, Competition, Pool, Winner) VALUES
(2025,'Senior','Senior Division 2','Willunga'),
(2024,'Senior','Senior Division 2','The Grange'),
(2023,'Senior','Senior Division 2','Thaxted Park'),
(2022,'Senior','Senior Division 2','Glenelg'),
(2021,'Senior','Senior Division 2','Kooyonga'),
(2020,'Senior','Senior Division 2','Glenelg')");

            // Senior Pennant — Division 3
            migrationBuilder.Sql(@"INSERT INTO HonourRoll (Year, Competition, Pool, Winner) VALUES
(2025,'Senior','Senior Division 3','McCraken'),
(2024,'Senior','Senior Division 3','Willunga'),
(2023,'Senior','Senior Division 3','Flagstaff Hill'),
(2022,'Senior','Senior Division 3','The Stirling'),
(2021,'Senior','Senior Division 3','Mt Osmond'),
(2020,'Senior','Senior Division 3','Kooyonga')");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "HonourRoll");
            migrationBuilder.DropTable(name: "HonourRollNarratives");
        }
    }
}