// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SAPennant.API.Data;

#nullable disable

namespace SAPennant.API.Migrations.Postgres
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413032941_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RoundStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsSettled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastChecked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Pool")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Round")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("SettledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Year", "Pool", "Round")
                        .IsUnique();

                    b.ToTable("RoundStatuses");
                });

            modelBuilder.Entity("SAPennant.API.Models.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("SAPennant.API.Models.HonourRoll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Competition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pool")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Winner")
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("HonourRoll");
                });

            modelBuilder.Entity("SAPennant.API.Models.HonourRollNarrative", b =>
                {
                    b.Property<string>("Competition")
                        .HasColumnType("text");

                    b.Property<string>("Narrative")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Competition");

                    b.ToTable("HonourRollNarratives");
                });

            modelBuilder.Entity("SAPennant.API.Models.PennantMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AwayClub")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HomeClub")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsFinals")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSenior")
                        .HasColumnType("boolean");

                    b.Property<string>("OpponentClub")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OpponentHandicap")
                        .HasColumnType("text");

                    b.Property<string>("OpponentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlayerClub")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlayerHandicap")
                        .HasColumnType("text");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("PlayerWon")
                        .HasColumnType("boolean");

                    b.Property<string>("Pool")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Round")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Venue")
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerName");

                    b.HasIndex("Year", "IsFinals");

                    b.ToTable("PennantMatches");
                });

            modelBuilder.Entity("SAPennant.API.Models.Season", b =>
                {
                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<int?>("FinalsId")
                        .HasColumnType("integer");

                    b.Property<int>("RegularId")
                        .HasColumnType("integer");

                    b.Property<int?>("SeniorFinalsId")
                        .HasColumnType("integer");

                    b.Property<int?>("SeniorRegularId")
                        .HasColumnType("integer");

                    b.HasKey("Year");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("SAPennant.API.Models.SyncLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SyncLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
